// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/list-panel/CRMSidebar.tsx": () => import("../components/mockups/list-panel/CRMSidebar.tsx"),
  "./components/mockups/list-panel/DocumentDrawer.tsx": () => import("../components/mockups/list-panel/DocumentDrawer.tsx"),
  "./components/mockups/list-panel/SpotlightPanel.tsx": () => import("../components/mockups/list-panel/SpotlightPanel.tsx"),
  "./components/mockups/rec-cards/CompactFeed.tsx": () => import("../components/mockups/rec-cards/CompactFeed.tsx"),
  "./components/mockups/rec-cards/HorizontalSplit.tsx": () => import("../components/mockups/rec-cards/HorizontalSplit.tsx"),
  "./components/mockups/rec-cards/PortraitHero.tsx": () => import("../components/mockups/rec-cards/PortraitHero.tsx")
};
