// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-layouts/CenteredStage.tsx": () => import("../components/mockups/homepage-layouts/CenteredStage.tsx"),
  "./components/mockups/homepage-layouts/EditorialAsymmetry.tsx": () => import("../components/mockups/homepage-layouts/EditorialAsymmetry.tsx"),
  "./components/mockups/homepage-layouts/ImmersiveScroll.tsx": () => import("../components/mockups/homepage-layouts/ImmersiveScroll.tsx")
};
